spring:
  application:
    name: "couver"
  docker:
    compose:
      enabled: true
      file: "compose.yaml"
  #JPA
  data:
    jpa:
      repositories:
        enabled: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
          format_sql: true
          use_sql_comments: true
      hibernate:
        ddl-auto: none
        show_sql: true
    datasource: #database configuration
      url: jdbc:postgresql://localhost:5070/couverdb
      username: root
      password: password
      driver-class-name: org.postgresql.Driver
  flyway: #flyway migration
    enabled: true
    encoding: UTF-8
    url: jdbc:postgresql://localhost:5070/couverdb
    user: root
    password: password
    execute-in-transaction: true
    locations: classpath:db/migration
    connect-retries: 5
    create-schema: true
    schemas: app_sc
    default-schema: app_sc
    sql-migration-prefix: VR
  # for jwt
  app:
    jwt:
      secret: "5da7abccd68264a5dadf70e16ccd2a48e5174651a08af2a366f8a28e39c88c0c"
      expirationMs: 180000
server:
  port: 8080